### ISSUE TITLE
issue with python

### ISSUE THREAD

**Issue by assolutooccidentale** [AbhyudayaSharma/MailPrinter#1]
i know it's not your fault but
i am trying to install your script, but python won't cooperate
i've installed setuptools
but
as i lunch ./setup.py install, after some many lines i get this :

Installed /usr/local/lib/python3.9/dist-packages/mailprinter-0.0.0-py3.9.egg
Processing dependencies for mailprinter==0.0.0
Searching for pycups
Reading https://pypi.org/simple/pycups/
Downloading https://files.pythonhosted.org/packages/0c/bb/82546806a86dc16f5eeb76f62ffdc42cce3d43aacd4e25a8b5300eec0263/pycups-2.0.1.tar.gz#sha256=57434ce5f62548eb12949ca8217f066f4eeb21a5d6ab8b13471dce350e380c90
Best match: pycups 2.0.1
Processing pycups-2.0.1.tar.gz
Writing /tmp/easy_install-8hf18rjq/pycups-2.0.1/setup.cfg
Running pycups-2.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8hf18rjq/pycups-2.0.1/egg-dist-tmp-qtfcjvsu
In file included from cupsconnection.c:22:
cupsconnection.h:25:10: fatal error: Python.h: No such file or directory
   25 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command '/usr/bin/arm-linux-gnueabi-gcc' failed with exit code 1

have you any clue what is going on?

**Comment by AbhyudayaSharma** [comment]
@assolutooccidentale Does this help? https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by assolutooccidentale** [comment]
heavens.. i  was missing python3-dev... though i had python2-dev and python3.9-dev.....
thank you a thousand
