### ISSUE TITLE
Invalid configuration detected

### ISSUE THREAD

**Issue by assolutooccidentale** [AbhyudayaSharma/MailPrinter#2]
hi, still me
i've sucessfully instlaled the scritp, configured the .json file, but everytime i run the python3 mailprinter i get
Invalid configuration detected!

i've checked: json seems correct:
{
  "IMAP_port": 993,
  "IMAP_server": mail.federcasapescara.it",
  "SSL_required": true,
  "printer_name":  "MFCL6900DW_slowlinux",
  "send_receive_interval": 1800
}
my provider is [fastnom](https://www.fastnom.it/clients/knowledgebase/209/Configurazione-posta-elettronica-es-Outlook-Thunderbird-Mail.html) 

`Posta in arrivo (POP3): mail.tuodominio.com`
`Posta in arrivo (IMAP): mail.tuodominio.com`
`Posta in uscita (SMTP): mail.tuodominio.com`
`Porta POP3: 995`
`Porta IMAP: 993`
`Porta SMTP: 587`

`export MAIL_PRINTER_USERNAME="xx@federcasapescara.it"`
`export MAIL_PRINTER_PASSWORD="password"`
`MailPrinter git:(master) ✗ python3 mailprinter`
`Invalid configuration detected!`

i've tried to use a gmail mail, but outcome was the same
i've tried to change printer name, but the same

jsut wondering.. in cups web interface i need to fetch the queue name, which incidentally is equal to description, needn't i?

**Comment by AbhyudayaSharma** [comment]
Your JSON seems to be invalid. `"IMAP_server": mail.federcasapescara.it"` should be `"IMAP_server": "mail.federcasapescara.it"`. Note the missing `"`.

**Comment by assolutooccidentale** [comment]
i've added the `"`, but outcome is the very same

**Comment by assolutooccidentale** [comment]
uh
seems like something is going on
though `MailPrinter is now running...` has been on for a while so far

**Comment by assolutooccidentale** [comment]
ok, my bad.. you can close this issue
